# Generated by Django 6.0 on 2026-02-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.FileField(blank=True, help_text='Upload MP4 file (dev / small projects)', null=True, upload_to='movies/videos/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_url',
            field=models.URLField(blank=True, help_text='External video URL (CDN / Cloudinary / S3)', null=True),
        ),
    ]
